### ISSUE TITLE
Train_Test_data not defined

### ISSUE THREAD

**Issue by urstrulykkr** [urstrulykkr/K-Nearest-Neighbours-model#2]
Ensure that the dataframe's being properly defined.

**Comment by rowhitswami** [comment]
I'd like to take this up :blush:

**Comment by urstrulykkr** [comment]
Hi @rowhitswami  
I'm sorry the issue's been fixed just now.
Thank you for your interest :)
Good luck!

**Comment by rowhitswami** [comment]
You can merge my PR
